# Generated by Django 3.0 on 2019-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makarena', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funds',
            new_name='Fund',
        ),
        migrations.RemoveField(
            model_name='user',
            name='value',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.IntegerField(choices=[(0, 'Unexpected'), (5, 'Family'), (6, 'Education'), (7, 'House'), (4, 'Technologies'), (3, 'Hobbies'), (2, 'Shopping'), (1, 'Car')], default=0),
        ),
    ]
